---
title: "Week 11 Principal Component Analysis Chenlu Zhang"
author: "Chenlu Zhang"
date: "7/26/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}


#install.packages("devtools")
library(devtools)
#install_github("vqv/ggbiplot")
#install.packages("ggplot2")
library("ggplot2")
library(ggbiplot)

#create df mtcars.pca and summarize a statistical table
mtcars.pca <- prcomp(mtcars[,c(1:7,10,11)], center = TRUE,scale. = TRUE)
summary(mtcars.pca)
str(mtcars.pca)

#install plyr and dplyr packages
library(plyr)
library(dplyr)
ggbiplot(mtcars.pca)
```


Next we use ggbiplot to plot some graphs for mtcars.pca generated above.


```{r}
#plot mtcars.pca
ggbiplot(mtcars.pca, labels=rownames(mtcars))

#add country origin and set ellipse to true
mtcars.country <- c(rep("Japan", 3), rep("US",4), rep("Europe", 7),rep("US",3), "Europe", rep("Japan", 3), rep("US",4), rep("Europe", 3), "US", rep("Europe", 3))

ggbiplot(mtcars.pca,ellipse=TRUE, labels=rownames(mtcars), groups=mtcars.country)

#set c(3,4)
ggbiplot(mtcars.pca,ellipse=TRUE,choices=c(3,4), labels=rownames(mtcars), groups=mtcars.country)

#more complex ggbiplot with titles and theme
ggbiplot(mtcars.pca,ellipse=TRUE,obs.scale = 1, var.scale = 1,  labels=rownames(mtcars), groups=mtcars.country) +
  scale_colour_manual(name="Origin", values= c("forest green", "red3", "dark blue"))+
  ggtitle("PCA of mtcars dataset")+
  theme_minimal()+
  theme(legend.position = "bottom")



```


Create and plot mtcarsplus.pca grouped by countryplus.

```{r}

#create a vector called space.car
space.car <- c(1000,60,50,500,0,0.5,2.5,0,1,0,0)

#combine mtcars and space.car to mtcars.plus
mtcars.plus <- rbind(mtcars, space.car)

#create mtcars.countryplus and mtcarsplus.pca
mtcars.countryplus <- c(mtcars.country, "Jupiter")

#ready the pca dataset
mtcarsplus.pca <- prcomp(mtcars.plus[,c(1:7,10,11)], center = TRUE,scale. = TRUE)
mtcarsplus.pca

#plot mtcarsplus.pca using more complex inputs (scale color, title and theme)
ggbiplot(mtcarsplus.pca, obs.scale = 1, var.scale = 1, ellipse = TRUE, circle = FALSE, var.axes=TRUE, labels=c(rownames(mtcars), "spacecar"), groups=mtcars.countryplus)+
  scale_colour_manual(name="Origin", values= c("forest green", "red3", "violet", "dark blue"))+
  ggtitle("PCA of mtcars dataset, with extra sample added")+
  theme_minimal()+
  theme(legend.position = "bottom")
```




```{r}
#create new df
s.sc <- scale(t(space.car[c(1:7,10,11)]), center= mtcars.pca$center)
s.pred <- s.sc %*% mtcars.pca$rotation

#use rbind to create new df
mtcars.plusproj.pca <- mtcars.pca
mtcars.plusproj.pca$x <- rbind(mtcars.plusproj.pca$x, s.pred)

#use ggbiplot to plot an ellipse graph grouped by country.
ggbiplot(mtcars.plusproj.pca, obs.scale = 1, var.scale = 1, ellipse = TRUE, circle = FALSE, var.axes=TRUE, labels=c(rownames(mtcars), "spacecar"), groups=mtcars.countryplus)+
  scale_colour_manual(name="Origin", values= c("forest green", "red3", "violet", "dark blue"))+
  ggtitle("PCA of mtcars dataset, with extra sample projected")+
  theme_minimal()+
  theme(legend.position = "bottom")
```

